{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fetching gdp_growth...\n",
      "Fetching gdp_per_capita...\n",
      "Fetching inflation...\n",
      "Fetching unemployment_rate...\n",
      "Fetching fdi_percent_gdp...\n",
      "Fetching population...\n",
      "Macro dataset created successfully.\n",
      "Shape: (6550, 8)\n",
      "       country  year  gdp_growth  gdp_per_capita  inflation  \\\n",
      "0  Afghanistan  2000         NaN      174.930991        NaN   \n",
      "1  Afghanistan  2001   -9.431974      138.706822        NaN   \n",
      "2  Afghanistan  2002   28.600001      178.954088        NaN   \n",
      "3  Afghanistan  2003    8.832278      198.871116        NaN   \n",
      "4  Afghanistan  2004    1.414118      221.763654        NaN   \n",
      "\n",
      "   unemployment_rate  fdi_percent_gdp  population  \n",
      "0              7.897         0.004828  20130327.0  \n",
      "1              7.973         0.024169  20284307.0  \n",
      "2              7.867         1.306950  21378117.0  \n",
      "3              7.844         1.278493  22733049.0  \n",
      "4              7.794         3.577104  23560654.0  \n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "# ---------------------------------\n",
    "# 1. Define Indicators\n",
    "# ---------------------------------\n",
    "\n",
    "INDICATORS = {\n",
    "    \"NY.GDP.MKTP.KD.ZG\": \"gdp_growth\",\n",
    "    \"NY.GDP.PCAP.CD\": \"gdp_per_capita\",\n",
    "    \"FP.CPI.TOTL.ZG\": \"inflation\",\n",
    "    \"SL.UEM.TOTL.ZS\": \"unemployment_rate\",\n",
    "    \"BX.KLT.DINV.WD.GD.ZS\": \"fdi_percent_gdp\",\n",
    "    \"SP.POP.TOTL\": \"population\"\n",
    "}\n",
    "\n",
    "START_YEAR = 2000\n",
    "END_YEAR = 2024\n",
    "\n",
    "\n",
    "# ---------------------------------\n",
    "# 2. Function to Fetch One Indicator\n",
    "# ---------------------------------\n",
    "\n",
    "def fetch_indicator(indicator_code, feature_name):\n",
    "    print(f\"Fetching {feature_name}...\")\n",
    "\n",
    "    url = f\"https://api.worldbank.org/v2/country/all/indicator/{indicator_code}\"\n",
    "    params = {\n",
    "        \"format\": \"json\",\n",
    "        \"per_page\": 20000\n",
    "    }\n",
    "\n",
    "    response = requests.get(url, params=params)\n",
    "    data = response.json()\n",
    "\n",
    "    if len(data) < 2:\n",
    "        print(f\"No data returned for {feature_name}\")\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    records = data[1]\n",
    "\n",
    "    df = pd.DataFrame(records)\n",
    "\n",
    "    # Extract relevant columns\n",
    "    df = df[[\"country\", \"date\", \"value\"]]\n",
    "\n",
    "    df[\"country\"] = df[\"country\"].apply(lambda x: x[\"value\"])\n",
    "    df.rename(columns={\"date\": \"year\", \"value\": feature_name}, inplace=True)\n",
    "\n",
    "    df[\"year\"] = df[\"year\"].astype(int)\n",
    "\n",
    "    # Filter years\n",
    "    df = df[(df[\"year\"] >= START_YEAR) & (df[\"year\"] <= END_YEAR)]\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ---------------------------------\n",
    "# 3. Fetch All Indicators\n",
    "# ---------------------------------\n",
    "\n",
    "macro_df = None\n",
    "\n",
    "for code, name in INDICATORS.items():\n",
    "    indicator_df = fetch_indicator(code, name)\n",
    "\n",
    "    if macro_df is None:\n",
    "        macro_df = indicator_df\n",
    "    else:\n",
    "        macro_df = macro_df.merge(\n",
    "            indicator_df,\n",
    "            on=[\"country\", \"year\"],\n",
    "            how=\"outer\"\n",
    "        )\n",
    "\n",
    "# ---------------------------------\n",
    "# 4. Remove Aggregated Regions\n",
    "# ---------------------------------\n",
    "\n",
    "aggregates = [\n",
    "    \"World\",\n",
    "    \"High income\",\n",
    "    \"Low income\",\n",
    "    \"Middle income\"\n",
    "]\n",
    "\n",
    "macro_df = macro_df[~macro_df[\"country\"].isin(aggregates)]\n",
    "\n",
    "# ---------------------------------\n",
    "# 5. Sort & Forward Fill\n",
    "# ---------------------------------\n",
    "\n",
    "macro_df = macro_df.sort_values([\"country\", \"year\"])\n",
    "\n",
    "macro_df = (\n",
    "    macro_df.groupby(\"country\")\n",
    "    .apply(lambda x: x.ffill())\n",
    "    .reset_index(drop=True)\n",
    ")\n",
    "\n",
    "# ---------------------------------\n",
    "# 6. Save\n",
    "# ---------------------------------\n",
    "\n",
    "macro_df.to_csv(\"macro_data.csv\", index=False)\n",
    "\n",
    "print(\"Macro dataset created successfully.\")\n",
    "print(\"Shape:\", macro_df.shape)\n",
    "print(macro_df.head())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (learn-env)",
   "language": "python",
   "name": "learn-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
