{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "3a984c63-4230-4989-b5d4-4ffda12896db",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collected 20 startup articles so far...\n",
      "Collected 40 startup articles so far...\n",
      "Collected 60 startup articles so far...\n",
      "Collected 80 startup articles so far...\n",
      "Collected 100 startup articles so far...\n",
      "Collected 120 startup articles so far...\n",
      "Collected 140 startup articles so far...\n",
      "Collected 160 startup articles so far...\n",
      "Collected 180 startup articles so far...\n",
      "Collected 200 startup articles so far...\n",
      "Collected 220 startup articles so far...\n",
      "Collected 240 startup articles so far...\n",
      "Collected 260 startup articles so far...\n",
      "Collected 280 startup articles so far...\n",
      "Collected 300 startup articles so far...\n",
      "Collected 320 startup articles so far...\n",
      "Collected 340 startup articles so far...\n",
      "Collected 360 startup articles so far...\n",
      "Collected 380 startup articles so far...\n",
      "Collected 400 startup articles so far...\n",
      "Collected 420 startup articles so far...\n",
      "Collected 440 startup articles so far...\n",
      "Collected 460 startup articles so far...\n",
      "Collected 480 startup articles so far...\n",
      "Collected 500 startup articles so far...\n",
      "Collected 520 startup articles so far...\n",
      "Collected 540 startup articles so far...\n",
      "Collected 560 startup articles so far...\n",
      "Collected 580 startup articles so far...\n",
      "Collected 600 startup articles so far...\n",
      "Collected 620 startup articles so far...\n",
      "Collected 640 startup articles so far...\n",
      "Collected 660 startup articles so far...\n",
      "Collected 680 startup articles so far...\n",
      "Collected 700 startup articles so far...\n",
      "Collected 720 startup articles so far...\n",
      "Collected 740 startup articles so far...\n",
      "Collected 760 startup articles so far...\n",
      "Collected 780 startup articles so far...\n",
      "Collected 800 startup articles so far...\n",
      "Total startup articles collected: 800\n",
      "{'startup_name': 'Why Paradigm built a spreadsheet with an AI agent in every cell', 'funding': '$5', 'industry': None, 'published': 'Mon, 18 Aug 2025 15:00:55 +0000', 'link': 'https://techcrunch.com/2025/08/18/why-paradigm-built-a-spreadsheet-with-an-ai-agent-in-every-cell/'}\n",
      "{'startup_name': 'Tailor, a ‘headless’ ERP startup,', 'funding': '$22M', 'industry': None, 'published': 'Mon, 30 Jun 2025 18:00:00 +0000', 'link': 'https://techcrunch.com/2025/06/30/tailor-a-headless-erp-startup-raises-22m-series-a/'}\n",
      "{'startup_name': 'Google co-founder Larry Page reportedly has a new AI startup', 'funding': None, 'industry': None, 'published': 'Thu, 06 Mar 2025 22:17:54 +0000', 'link': 'https://techcrunch.com/2025/03/06/google-co-founder-larry-page-reportedly-has-a-new-ai-startup/'}\n",
      "{'startup_name': 'Guidde taps AI to help create software training videos', 'funding': None, 'industry': None, 'published': 'Wed, 19 Feb 2025 12:00:42 +0000', 'link': 'https://techcrunch.com/2025/02/19/guidde-taps-ai-to-help-create-software-training-videos/'}\n",
      "{'startup_name': 'Elon Musk’s AI company, xAI, said to be in talks to raise $10B', 'funding': '$10B', 'industry': None, 'published': 'Fri, 14 Feb 2025 19:54:01 +0000', 'link': 'https://techcrunch.com/2025/02/14/elon-musks-ai-company-xai-said-to-be-in-talks-to-raise-10b/'}\n"
     ]
    }
   ],
   "source": [
    "import feedparser\n",
    "import re\n",
    "import time\n",
    "\n",
    "def extract_funding(text):\n",
    "    \"\"\"Try to extract funding amount from text.\"\"\"\n",
    "    pattern = r'\\$[\\d,.]+[MB]?'  # e.g., $12M, $450,000\n",
    "    match = re.search(pattern, text)\n",
    "    return match.group(0) if match else None\n",
    "\n",
    "def extract_startup_name(title):\n",
    "    \"\"\"Simplistic: take first few words or before 'raises', 'startup', etc.\"\"\"\n",
    "    split_words = re.split(r' raises | startup | acquired | launches ', title, flags=re.IGNORECASE)\n",
    "    return split_words[0].strip()\n",
    "\n",
    "def scrape_phase1_techcrunch_rss(feed_url, max_entries=800):\n",
    "    articles = []\n",
    "    collected = 0\n",
    "\n",
    "    while collected < max_entries:\n",
    "        feed = feedparser.parse(feed_url)\n",
    "        \n",
    "        if not feed.entries:\n",
    "            print(\"No more entries found. Stopping.\")\n",
    "            break\n",
    "        \n",
    "        for entry in feed.entries:\n",
    "            title = entry.title\n",
    "            summary = entry.summary if 'summary' in entry else ''\n",
    "            startup_name = extract_startup_name(title)\n",
    "            funding = extract_funding(title + \" \" + summary)\n",
    "            \n",
    "            articles.append({\n",
    "                'startup_name': startup_name,\n",
    "                'funding': funding,\n",
    "                'industry': None,  # Could be filled with keyword matching later\n",
    "                'published': entry.published if 'published' in entry else '',\n",
    "                'link': entry.link\n",
    "            })\n",
    "            \n",
    "            collected += 1\n",
    "            if collected >= max_entries:\n",
    "                break\n",
    "\n",
    "        print(f\"Collected {collected} startup articles so far...\")\n",
    "        time.sleep(1)  # polite delay\n",
    "\n",
    "    print(f\"Total startup articles collected: {len(articles)}\")\n",
    "    return articles\n",
    "\n",
    "# Usage\n",
    "feed_url = \"https://techcrunch.com/tag/startup/feed/\"\n",
    "phase1_data = scrape_phase1_techcrunch_rss(feed_url, max_entries=800)\n",
    "\n",
    "# Check first 5 rows\n",
    "for row in phase1_data[:5]:\n",
    "    print(row)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "69de37e1-92a6-44bc-bd8b-1d61e6ffbc78",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>startup_name</th>\n",
       "      <th>funding</th>\n",
       "      <th>industry</th>\n",
       "      <th>published</th>\n",
       "      <th>link</th>\n",
       "      <th>funding_amount</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Why Paradigm built a spreadsheet with an AI ag...</td>\n",
       "      <td>$5</td>\n",
       "      <td>None</td>\n",
       "      <td>2025-08-18 15:00:55+00:00</td>\n",
       "      <td>https://techcrunch.com/2025/08/18/why-paradigm...</td>\n",
       "      <td>5.000000e+00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Tailor, a ‘headless’ ERP startup</td>\n",
       "      <td>$22M</td>\n",
       "      <td>None</td>\n",
       "      <td>2025-06-30 18:00:00+00:00</td>\n",
       "      <td>https://techcrunch.com/2025/06/30/tailor-a-hea...</td>\n",
       "      <td>2.200000e+07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Google co-founder Larry Page reportedly has a ...</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>2025-03-06 22:17:54+00:00</td>\n",
       "      <td>https://techcrunch.com/2025/03/06/google-co-fo...</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Guidde taps AI to help create software trainin...</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>2025-02-19 12:00:42+00:00</td>\n",
       "      <td>https://techcrunch.com/2025/02/19/guidde-taps-...</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Elon Musk’s AI company, xAI, said to be in tal...</td>\n",
       "      <td>$10B</td>\n",
       "      <td>None</td>\n",
       "      <td>2025-02-14 19:54:01+00:00</td>\n",
       "      <td>https://techcrunch.com/2025/02/14/elon-musks-a...</td>\n",
       "      <td>1.000000e+10</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        startup_name funding industry  \\\n",
       "0  Why Paradigm built a spreadsheet with an AI ag...      $5     None   \n",
       "1                   Tailor, a ‘headless’ ERP startup    $22M     None   \n",
       "2  Google co-founder Larry Page reportedly has a ...    None     None   \n",
       "3  Guidde taps AI to help create software trainin...    None     None   \n",
       "4  Elon Musk’s AI company, xAI, said to be in tal...    $10B     None   \n",
       "\n",
       "                  published  \\\n",
       "0 2025-08-18 15:00:55+00:00   \n",
       "1 2025-06-30 18:00:00+00:00   \n",
       "2 2025-03-06 22:17:54+00:00   \n",
       "3 2025-02-19 12:00:42+00:00   \n",
       "4 2025-02-14 19:54:01+00:00   \n",
       "\n",
       "                                                link  funding_amount  \n",
       "0  https://techcrunch.com/2025/08/18/why-paradigm...    5.000000e+00  \n",
       "1  https://techcrunch.com/2025/06/30/tailor-a-hea...    2.200000e+07  \n",
       "2  https://techcrunch.com/2025/03/06/google-co-fo...             NaN  \n",
       "3  https://techcrunch.com/2025/02/19/guidde-taps-...             NaN  \n",
       "4  https://techcrunch.com/2025/02/14/elon-musks-a...    1.000000e+10  "
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.DataFrame(phase1_data)\n",
    "\n",
    "# Clean funding\n",
    "def funding_to_number(funding):\n",
    "    if not funding:\n",
    "        return None\n",
    "    funding = funding.replace('$','').replace(',','').upper()\n",
    "    if 'B' in funding:\n",
    "        return float(funding.replace('B','')) * 1e9\n",
    "    elif 'M' in funding:\n",
    "        return float(funding.replace('M','')) * 1e6\n",
    "    else:\n",
    "        try:\n",
    "            return float(funding)\n",
    "        except:\n",
    "            return None\n",
    "\n",
    "df['funding_amount'] = df['funding'].apply(funding_to_number)\n",
    "\n",
    "# Clean startup names\n",
    "df['startup_name'] = df['startup_name'].str.replace(r',$','', regex=True).str.strip()\n",
    "\n",
    "# Convert published date\n",
    "df['published'] = pd.to_datetime(df['published'])\n",
    "\n",
    "df.head()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "e533cb15-10e1-4267-929b-bc460760cdd6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 800 entries, 0 to 799\n",
      "Data columns (total 6 columns):\n",
      " #   Column          Non-Null Count  Dtype              \n",
      "---  ------          --------------  -----              \n",
      " 0   startup_name    800 non-null    object             \n",
      " 1   funding         440 non-null    object             \n",
      " 2   industry        0 non-null      object             \n",
      " 3   published       800 non-null    datetime64[ns, UTC]\n",
      " 4   link            800 non-null    object             \n",
      " 5   funding_amount  440 non-null    float64            \n",
      "dtypes: datetime64[ns, UTC](1), float64(1), object(4)\n",
      "memory usage: 37.6+ KB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
